### ISSUE TITLE
'constructor' not allowed as a variable name

### ISSUE THREAD

**Issue by yallop** [andrewray/iocaml#32] opened 2015-02-26 10:36 UTC
To reproduce: type

```
let constructor = 3
```

in a notebook (e.g. http://andrewray.github.io/iocamljs/min.html).  The cell freezes after the 'o'.

**Comment by andrewray** [comment] 2015-02-26 10:58
Confirmed.  Seems to be a problem with the codemirror editor as it can be also seen here;

http://codemirror.net/mode/mllike/index.html

codemirror/CodeMirror#3106

**Comment by andrewray** [comment] 2015-02-26 11:16
Fixed in repo and online.

**Closed by andrewray** 2015-02-26 11:16 UTC

**Comment by yallop** [comment] 2015-02-26 13:13
Thanks!
